assertionFailure("assertionFailure(:_)関数は有効です")
print("assertionFailure(_:)関数は無効です")
